### ISSUE TITLE
test_new_no_args fails on PyPy2.7

### ISSUE THREAD

**Issue by mgorny** [python/typing#671] opened 2019-08-22 16:34 UTC
```
$ pypy --version
Python 2.7.13 (8cdda8b8cdb8ff29d9e620cccd6c5edd2f2a23ec, Apr 19 2019, 18:39:17)
[PyPy 7.1.1 with GCC 7.4.0]
$ cd python2 && pypy -m unittest discover
.....................................................................................................F...................................................................................................................................
======================================================================
FAIL: test_new_no_args (test_typing.GenericTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/typing/python2/test_typing.py", line 1825, in test_new_no_args
    A('foo')
AssertionError: TypeError not raised

----------------------------------------------------------------------
Ran 233 tests in 0.759s

FAILED (failures=1)
```

Same result with `tox`, after copying `testenv:py27` to `testenv:pypy`.

**Comment by ilevkivskyi** [comment] 2019-08-22 16:46
Why do you think it is not a PyPy bug? In any case, PyPy is not officially supported by this backport. So unless you are willing to provide a reasonable fix/workaround, I am going to close this.

**Comment by mgorny** [comment] 2019-08-22 17:48
I don't know, I was hoping you'd be able to tell me. 3.6.4 worked fine.

**Comment by nickgaya** [comment] 2019-10-25 10:58
Here is the relevant difference between CPython and PyPy.

In CPython:
```
>>> from typing import Generic, TypeVar
>>> T = TypeVar('T')
>>> class A(Generic[T]):
...     pass
... 
>>> A.__init__ is object.__init__
True
```

In PyPy:
```
>>>> from typing import Generic, TypeVar
>>>> T = TypeVar('T')
>>>> class A(Generic[T]):
....     pass
....     
>>>> A.__init__ is object.__init__
False
```

This means that in PyPy, `typing._generic_new(A, 'foo')` will call `object.__new__(A)` instead of `object.__new__(A, 'foo')` as in CPython, which would raise a `TypeError`.

Moreover, in both CPython and PyPy, `object.__init__(object.__new__(A), 'foo')` succeeds, even though ordinarily `object.__init__()` raises a `TypeError` if given extra arguments.  This is actually the crux of the problem.

We can produce similar behavior in CPython like this:
```
class B(Generic[T]):
    def __init__(self, *args, **kwargs):
        return super(B, self).__init__(*args, **kwargs)
```

It looks like `A` and `B` should be equivalent, but in CPython, `A('foo')` raises a `TypeError` while `B('foo')` does not.  In PyPy, `A` and `B` behave the the same, which is arguably more consistent.

So the central question is: Why doesn't `object.__init__(object.__new__(A), 'foo')` raise an exception?

**Comment by nickgaya** [comment] 2019-10-25 11:12
Related: https://github.com/python/typing/pull/560, https://github.com/python/cpython/pull/6758

@ilevkivskyi What is the reason for adding the `__init__` check in `typing._generic_new()`?

**Comment by nickgaya** [comment] 2019-10-25 12:04
Hm, I found the answer to my question [here](https://github.com/python/cpython/pull/6732#discussion_r187018506):
> This is definitely a wart -- object.__init__ and object.__new__ each ignore extra arguments only when the other is overridden (and they themselves are not).

I'll ponder this a bit to see if there's a different solution that would work for both A and B.

**Comment by mgorny** [comment] 2019-11-21 10:08
Could you hint me a bit on how to handle this downstream? Is this a regression in the new version, or merely a thing that wasn't tested before? Is this something critical to functionality, or can I just ignore the test failure on PyPy for the time being?

**Comment by gvanrossum** [comment] 2019-12-02 23:53
It's not a regression in typing.py. I don't know what changed (the test or the typing.py module) but it looks like it's failing due to the *absence* of an expected exception, which doesn't sound like the end of the world. Maybe you can try deleting these two lines from the failing test:
```
        with self.assertRaises(TypeError):
            A('foo')
```
If it then passes, I wouldn't worry (and we might accept a PR that skips those two lines if PyPy is detected).

For more details just carefully read this issue from the top, it's all there.

**Comment by srittau** [comment] 2021-11-04 12:14
The typing backport has been removed from this repository, making this issue obsolete.

**Closed by srittau** 2021-11-04 12:14 UTC
