### ISSUE TITLE
a way to get the type of a variable

### ISSUE THREAD

**Issue by DetachHead** [python/typing#915] opened 2021-11-02 06:01 UTC
in my use case if have a class with several generics, i want a convenient way to get the type of an instance, but it doesn't seem to be possible in any type checkers
```py
from typing import Generic, TypeVar

T = TypeVar("T")

class Foo(Generic[T]):
    ...

foo = Foo[int]()
bar = Foo[str]()

baz: type[foo] | type[bar] = ...
```
mypy errors:
```
main.py:11: error: Variable "__main__.foo" is not valid as a type
main.py:11: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:11: error: Variable "__main__.bar" is not valid as a type
```

the alternative is to duplicate the types (which is annoying if the type annotation is large) or create a type alias, which is a pain

in typescript you can use `typeof`
```ts
interface Foo<T> {}

declare const foo: Foo<number>
declare const bar: Foo<string>

declare const baz: typeof foo | typeof bar
```

PS: i tried `baz: reveal_type(foo) = foo`, but no luck ![image](https://user-images.githubusercontent.com/57028336/139794340-ca9c86d7-1b18-4aa2-baac-dc77bb9aa368.png)

**Comment by erictraut** [comment] 2021-11-02 06:14
I think you've already identified the workarounds that are available in Python today:
1. Specify the type explicitly within the annotation
2. Define a type alias and use that in the annotation

I wouldn't expect `type[foo]` to work. The equivalent of TypeScript's `typeof foo` would be `type(foo)`. Currently that's not allowed because call expressions are not permitted within type annotation expressions. There are good reasons for that limitation, and (speaking as a type checker maintainer) I'd recommend that we leave that limitation in place and not create an exception.

This use case is not common, so it's reasonable that you create a type alias in this circumstance.

**Comment by srittau** [comment] 2021-11-04 14:38
I believe this is a duplicate of #769.

**Closed by srittau** 2021-11-04 14:38 UTC
Labels: resolution: duplicate, topic: feature
