### ISSUE TITLE
NamedTuple with a TypeVar

### ISSUE THREAD

**Issue by mehdigmira** [python/typing#588] opened 2018-10-23 10:03 UTC
Hello,

This is a question concerning NamedTuples. I'm using python 3.5.

Is there a way to create a namedtuple that relies on a typevar ?

I've tried this:

```python
from typing import Optional, TypeVar, NamedTuple, Dict, Tuple, Generic

MetaDataT = TypeVar("MetaDataT")

def f(m: MetaDataT):
    State = NamedTuple("State", [("metadata", MetaDataT), ("new", bool), ("update", MetaDataT)])
```

But mypy complains by saying: `error: 'MetaDataT' is a type variable and only valid in type context`

So I tried to declare `State` outside of the function such as:

```python
from typing import Optional, TypeVar, NamedTuple, Dict, Tuple, Generic

MetaDataT = TypeVar("MetaDataT")

State = NamedTuple("State", [("metadata", MetaDataT), ("new", bool), ("update", MetaDataT)])
```

But this time mypy complains by saying: `error: Invalid type "debug.MetaDataT"`

I guess something like this coul work:

```python
class S(NamedTuple, Generic[MetaDataT]):
     pass
```

But I'm using python 3.5 and this syntax is not supported.

**Comment by JelleZijlstra** [comment] 2018-10-23 10:53
(This is a limitation in mypy though, not in the type system itself, so no need to keep this issue open.)

**Comment by ilevkivskyi** [comment] 2018-10-23 17:08
Yes, this is a duplicate of https://github.com/python/mypy/issues/685.

**Closed by ilevkivskyi** 2018-10-23 17:08 UTC
