### ISSUE TITLE
implement string literal type

### ISSUE THREAD

**Issue by chantisnake** [python/typing#494] opened 2017-10-31 15:35 UTC
Despite the recent introduction of Enum to python standard library. there are still tons and tons of packages using fake enum (int or string)

Typescript provides the string literal type, which will be super helpful in this situation.

documentation on string literal type can be found here:
https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by ilevkivskyi** [comment] 2017-10-31 16:06
Duplicate of https://github.com/python/typing/issues/478

**Closed by ilevkivskyi** 2017-10-31 16:06 UTC
