### ISSUE TITLE
It should be possible to describe an expression as useable according to two types

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [python/typing#529] opened 2018-01-18 16:04 UTC
When we designed gRPC Python we wanted to keep the API surface as minimal as possible, so we have a few places where rather than introduce a new type that is merely the union of two types we simply say "this value is usable according to two types". Consider [the return value of `grpc.UnaryUnaryMultiCallable.future`: "An object that is both a [`grpc.`]`Call` for the RPC and a [`grpc.`]`Future`."](https://github.com/grpc/grpc/blob/5eb6148ab4e95ea472af2033bd976317992fe18f/src/python/grpcio/grpc/__init__.py#L666-L671).

We'd like to use pytype in gRPC Python but it will need to understand code shaped like this.

**Comment by JukkaL** [comment] 2018-01-18 16:19
It looks like what you want is an intersection type rather than union -- a union type can be a `Call` or a `Future`. There's no direct way to represent an intersection, but defining an ABC that multiply inherits from `Call` and `Future` might be an option. Are you planning to release stubs for gRPC or just use pytype internally? The most suitable approach may depend on this decision. I'd recommend releasing stub files so that all type checking tools will be able to type check code that uses gRPC.

Additionally, the `typing_extensions` module provides `Protocol` classes (structural types), and you can multiply inherit from protocols. Protocols are still not supported by pytype, as far as I know.

**Comment by matthiaskramm** [comment] 2018-01-18 18:22
> Protocols are still not supported by pytype, as far as I know.

They're supported by pytype. By default, we don't yet automatically infer them when generating pyi files, but that's a different story.

**Comment by JukkaL** [comment] 2018-01-18 18:30
> They're supported by pytype. By default, we don't yet automatically infer them when generating pyi files, but that's a different story.

Excellent! I wonder how far PyCharm is in implementing protocols -- it would be great to be able to start looking at using them more in typeshed. @vlasovskikh

**Comment by vlasovskikh** [comment] 2018-01-18 21:19
@JukkaL Protocols will appear in PyCharm this spring. At the moment we use an older snapshot of Typeshed, so we’re fine with introducing protocols in the master branch of Typeshed.

**Comment by ilevkivskyi** [comment] 2019-02-04 09:02
Closing as a duplicate of https://github.com/python/typing/issues/213

**Closed by ilevkivskyi** 2019-02-04 09:02 UTC
