### ISSUE TITLE
Support list comprehension for `TypeVarTuple`

### ISSUE THREAD

**Issue by zen-xu** [python/typing#1745] opened 2024-05-23 01:52 UTC
Imagine there's a scenario, I need to accept a bunch of different type objects, and then return these objects boxed in a tuple of a generic type. Currently, this can only be achieved by manually writing overload, is there a more pythonic solution?

```python
from typing import Generic
from typing import TypeVar
from typing import overload


_T = TypeVar("_T")
_T0 = TypeVar("_T0")
_T1 = TypeVar("_T1")
_T2 = TypeVar("_T2")


class ObjectRef(Generic[_T]): ...


@overload
def put(items: tuple[_T0]) -> tuple[ObjectRef[_T0]]: ...


@overload
def put(items: tuple[_T0, _T1]) -> tuple[ObjectRef[_T0], ObjectRef[_T1]]: ...


@overload
def put(
    items: tuple[_T0, _T1, _T2],
) -> tuple[ObjectRef[_T0], ObjectRef[_T1], ObjectRef[_T2]]: ...


@overload
def get(refs: tuple[ObjectRef[_T0]]) -> tuple[_T0]: ...


@overload
def get(refs: tuple[ObjectRef[_T0], ObjectRef[_T1]]) -> tuple[_T0, _T1]: ...


@overload
def get(
    refs: tuple[ObjectRef[_T0], ObjectRef[_T1], ObjectRef[_T2]],
) -> tuple[_T0, _T1, _T2]: ...

```

**Comment by zen-xu** [comment] 2024-05-23 01:57
If the following solution could be supported, that would be great

```python
from typing import Generic
from typing import TypeVar
from typing import TypeVarTuple


_T = TypeVar("_T")
_Ts = TypeVarTuple("_Ts")


class ObjectRef(Generic[_T]): ...

def put(items: tuple[*_Ts]) -> tuple[ObjectRef[_T] for _T in _Ts]: ...

# backport to old python version
# def put(items: tuple[*_Ts]) -> tuple["ObjectRef[_T] for _T in _Ts"]: ...
```

**Comment by carljm** [comment] 2024-05-23 03:05
I think this is a duplicate of https://github.com/python/typing/issues/1216

**Closed** 2024-05-23 03:06 UTC
Labels: topic: other
