### ISSUE TITLE
Correct way to use typing when a value may be cast

### ISSUE THREAD

**Issue by kura** [python/typing#539] opened 2018-02-27 11:55 UTC
I need the ability to read values from a config file where the type may be interpreted as a string when the value is going to be cast to an int.

What would the correct way of doing this be?

Currently I use a setter to set the value in to the class and cast it.

```python
class A:

	...

	# read in data from the config file
	# start setting var -> value using the setters.

	...

	_timeout = 0  # type: int

	@property
	def timeout(self) -> int:
		return self._timeout

	@timeout.setter
	def timeout(self, timeout: int) -> None:
		self._timeout = int(timeout)
```

I'm pretty sure this isn't correct, but I'm unsure how exactly to change the typing in the setter signature to allow for a string that will be casted.

**Comment by gvanrossum** [comment] 2018-02-27 16:14
Looks like a duplicate of #3004. You'd want the setter arg to be declared as e.g. `Union[str, int]` but mypy won't accept that. You could move the conversion into a helper method (defeating much of the convenience of the property) or you could declare the property as returning `Any` (defeating the type checking of uses of the property). Sorry.

**Closed by gvanrossum** 2018-02-27 16:14 UTC

**Comment by kura** [comment] 2018-02-27 16:39
Alrighty, thanks @gvanrossum!
