### ISSUE TITLE
Internal error on NamedTuple factory

### ISSUE THREAD

**Issue by lbenezriravin** [python/typing#603] opened 2019-01-04 01:38 UTC
I'm trying to create a factory following the pattern here:
https://github.com/python/typing/issues/58#issuecomment-326240794

Big thank you to the maintainers. This is a pretty trivial issue -- just thought I'd post it since mypy asked me so nicely :)

Edit: fwiw, my workaround is to use a dataclass instead of a NamedTuple, and that works fine.

Environment:
```
$ pipenv run python --version
Python 3.7.1
$ pipenv graph
mypy==0.650
  - mypy-extensions [required: >=0.4.0,<0.5.0, installed: 0.4.1]
  - typed-ast [required: >=1.1.0,<1.2.0, installed: 1.1.1]
```

Reproduce with:
```
from typing import NamedTuple, Type, TypeVar

T = TypeVar('T', bound='TrivialClass')

class TrivialClass(NamedTuple):
    foo: int

    @classmethod
    def from_str(cls: Type[T], foo: str) -> T:
        return cls(int(foo))
```

Result:
```
$ pipenv run mypy ex.py --show-traceback
ex.py:10: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.650
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/main.py", line 92, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 156, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 206, in _build
    graph = dispatch(sources, manager)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 2232, in dispatch
    process_graph(graph, manager)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 2532, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 2655, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/build.py", line 1791, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 848, in accept
    return visitor.visit_class_def(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 1536, in visit_class_def
    self.accept(defn.defs)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 913, in accept
    return visitor.visit_block(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 1688, in visit_block
    self.accept(s)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 691, in accept
    return visitor.visit_decorator(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 3018, in visit_decorator
    self.check_func_item(e.func, name=e.func.name())
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 770, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 934, in check_func_def
    self.accept(item.body)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 913, in accept
    return visitor.visit_block(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 1688, in visit_block
    self.accept(s)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 1046, in accept
    return visitor.visit_return_stmt(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 2627, in visit_return_stmt
    self.check_return_stmt(s)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checker.py", line 2660, in check_return_stmt
    allow_none_return=allow_none_func_call)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 3067, in accept
    typ = node.accept(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/nodes.py", line 1421, in accept
    return visitor.visit_call_expr(self)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 229, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 296, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 633, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 767, in check_call
    callable_node, arg_messages)
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/checkexpr.py", line 675, in check_call
    if (callee.is_type_obj() and callee.type_object().is_abstract
  File "/home/user/.local/share/virtualenvs/myp-yC5yP7uq/lib/python3.7/site-packages/mypy/types.py", line 834, in type_object
    assert isinstance(ret, Instance)
AssertionError: 
ex.py:10: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment] 2019-01-04 09:39
Thanks for reporting! This is a duplicate of https://github.com/python/mypy/issues/5996

**Closed by ilevkivskyi** 2019-01-04 09:39 UTC
