### ISSUE TITLE
Generator optional parameters

### ISSUE THREAD

**Issue by YodaEmbedding** [python/typing#716] opened 2020-04-16 15:57 UTC
Can the last two parameters of `Generator[YieldType, SendType, ReturnType]` be made optional? Usually, one uses generators without them:

```python
def infinite_stream(start: int) -> Generator[int, None, None]:
    while True:
        yield start
        start += 1
```

`Iterator[YieldType]` also works, of course, but `Generator[YieldType]` is more specific.

See also: https://github.com/python/mypy/issues/4221

**Comment by gvanrossum** [comment] 2020-04-16 17:02
PEP 484 currently doesn't support optional arguments to generics (note that `Tuple[int, str]` is a special form, not just a generic type). But you can easily define a type alias, e.g.
```
from typing import *

T = TypeVar("T")

SimpleGenerator = Generator[T, None, None]

def foo() -> SimpleGenerator[int]:
    yield 0
    yield 1.1
```
This gives an error on `yield 1.1`:
```
t.py:9: error: Incompatible types in "yield" (actual type "float", expected type "int")
```
Using various `reveal_type()` calls I can also confirm that the type of `foo` is correct:
```
t.py:11: note: Revealed type is 'def () -> typing.Generator[builtins.int, None, None]'
t.py:12: note: Revealed type is 'typing.Generator[builtins.int, None, None]'
t.py:13: note: Revealed type is 'builtins.int*'
```

**Comment by JelleZijlstra** [comment] 2021-05-12 03:29
This is a duplicate of #307. (Generator is probably among the few standard ABCs for which default type parameters would make sense.)

**Comment by srittau** [comment] 2021-05-12 06:45
@JelleZijlstra These issues aren't duplicates. #307 is about `TypeVar(T, default=...)`, this issue about e.g. `Generator[int]`.

**Comment by JelleZijlstra** [comment] 2021-05-12 14:01
But you could use #307 to fix this issue. I guess they're not exact duplicates though.

**Comment by srittau** [comment] 2021-11-04 12:36
But it's a duplicate of https://bugs.python.org/issue31700. :) Closing again.

**Closed by srittau** 2021-11-04 12:36 UTC
Labels: resolution: duplicate, topic: feature
