### ISSUE TITLE
Callable type is missing the __signature__ attribute

### ISSUE THREAD

**Issue by jrideout** [python/typing#598] opened 2018-12-07 04:33 UTC
```
from typing import Callable

def test(f: Callable) -> None:
    f.__signature__ = ''

```

mypy returns:

```
error: "Callable[..., Any]" has no attribute "__signature__"
```

**Comment by jrideout** [comment] 2018-12-07 04:34
I'm dealing with issues related to #270, but it seems regardless of what direction that goes `__signature__` should be a recognized attribute of Callable

**Comment by ilevkivskyi** [comment] 2018-12-07 09:57
This is not really a `typing` problem, but a mypy problem. Essentially, this is just a duplicate of https://github.com/python/mypy/issues/5958

**Closed by ilevkivskyi** 2018-12-07 09:57 UTC
