### ISSUE TITLE
Cannot define a dict between TypeVars and types

### ISSUE THREAD

**Issue by mitar** [python/typing#520] opened 2017-12-18 13:44 UTC
The following fails:

```
import typing
typing.Dict[typing.TypeVar, type]
```

```
  File "/usr/lib/python3.6/typing.py", line 679, in inner
    return cached(*args, **kwds)
  File "/usr/lib/python3.6/typing.py", line 1106, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 1106, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 379, in _type_check
    isinstance(arg, TypingMeta) and arg._gorg in (Generic, _Protocol)
AttributeError: type object 'TypeVar' has no attribute '_gorg'
```

Python 3.6.3.

**Comment by ilevkivskyi** [comment] 2017-12-18 19:35
Things like this will not typecheck in static type checkers. But I think they should not crash at runtime.

Also this already works at runtime with PEP 560 (and corresponding CPython PR for ``typing``), so this is only a problem for the backport on PyPI.

**Comment by mitar** [comment] 2017-12-18 22:00
So what I am making here is literally a function which directly operates on `TypeVars`, it is just utility function to extract mapping between type vars and types from a generic so that at runtime code can check what types were used in the generic.

Current workaround is to define `typing.Dict[type, type]` but this is a bit ugly.

**Comment by ilevkivskyi** [comment] 2019-06-20 01:21
This is essentially (a more narrow) duplicate of https://github.com/python/typing/issues/492

**Closed by ilevkivskyi** 2019-06-20 01:21 UTC

**Comment by mitar** [comment] 2019-06-20 02:48
Hm, not sure how it is a duplicate of #492. What I am reporting here is that one cannot define a function and type check it if the function is operating on typing constructs themselves. So `TypeVar` instances can be saved into a Python dict. Why I cannot define such function?

Imagine that I extract all `TypeVar` values from `globals()` and make a dict of that and pass it to a function. How do I type that function which would receive such a dict.

**Comment by ilevkivskyi** [comment] 2019-06-20 08:42
You can't do this because there is a runtime limitation that all arguments to generic types, must be proper types, that issue proposes to completely remove this requirement.

**Comment by mitar** [comment] 2019-06-20 09:49
I mean, yes? If I cannot type some valid Python programs because of such limitation?
