### ISSUE TITLE
Uses for Intersection in type hints

### ISSUE THREAD

**Issue by ViktorSky** [python/typing#1511] opened 2023-11-24 00:45 UTC
The idea in proposing `Intersection` is to create type hints that support type transformations, since it is not possible to support this behavior without using inheritance.
Furthermore, it becomes much more complicated when trying to use it in overloads.

```python
from typing import TypeVar, Protocol, TYPE_CHECKING, dataclass_transform

ModelT = TypeVar("ModelT", bound=type)

class CreatedModel(Protocol):
    def dump(self) -> str: ...

@dataclass_transform()
def create_model(cls: ModelT) -> ModelT:
    ...  # adding attributes
    return cls

class CustomerModel:
    id: int
    name: str

if TYPE_CHECKING:
    assert issubclass(CustomerModel, CreatedModel)

cls_type = CustomerModel  #  type[<subclass of CustomerModel and CreatedModel>]
```
In this case, I assume that this tool `typing.Intersection` exists. It should work similar to `typing.Union`, but the actual type meets the arguments of this as protocols
```python
from typing import TypeVar, Protocol, dataclass_transform
from typing import Intersection  # not exist

ModelT = TypeVar("ModelT", bound=type)

class CreatedModel(Protocol):
    def dump(self) -> str: ...

@dataclass_transform()
def create_model(cls: ModelT) -> Intersection[ModelT, type[CreatedModel]]:
    ...
    return cls

@create_model
class CustomerModel:
    id: int
    name: str
```
This implementation would help the more efficient development of dynamic classes by linking with typevar so as not to lose a lot of information during its creation.

**Comment by ViktorSky** [comment] 2023-11-24 00:46
#1511

**Comment by JelleZijlstra** [comment] 2023-11-24 11:13
Duplicate of #213.

See also https://github.com/CarliJoy/intersection_examples where there is work towards a PEP on Intersection.

**Closed by JelleZijlstra** 2023-11-24 11:13 UTC
Labels: topic: feature
