### ISSUE TITLE
Type checking for **kwargs based on its use

### ISSUE THREAD

**Issue by mauvilsa** [python/typing#1213] opened 2022-06-17 15:43 UTC
Look at the following example:

```python
def some_function(f1: int):
    assert isinstance(f1, int)

def other_function(f0: str, **kwargs):
    assert isinstance(f0, str)
    some_function(**kwargs)

other_function(f0='a', f1='b')
```

I would expect a static type checker to warn that `f1='b'` is wrong because the type should be `int`. There shouldn't be a need to add a type to `**kwargs` since what is accepted can be deduced from how it is used. Note that `some_function` could be defined in another module and be used in multiple places, thus the "don't repeat yourself" and "separation of concerns" principles apply. Better to have the type for `f1` be only in the definition of `some_function` and not in the `**kwargs`.

I have seen that there are discussions about `TypedDict` for more precise typing of `**kwargs`. However, requiring to use `TypedDict` for the cases in which it can be inferred what `**kwargs` accepts, seems over-complicating things. This is yet another principle "keep it simple, stupid".

I previously created github issues (https://github.com/python/mypy/issues/12991, https://github.com/microsoft/pyright/issues/3583), wrote to the [python-ideas mailing list](https://mail.python.org/archives/list/python-ideas@python.org/thread/TEDDC7FU7TR6AESZT2NLHUYCKIJYFZTD/) and have been advised to come here. I have seen two reasons why this is problematic:
- "PEP 484 is very clear that if a parameter has no type annotation, it is meant to be interpreted as an implicit Any type"
- "type checkers are *required* to not check unannotated types (by PEP 484, ...). That's fundamental to the idea of gradual typing"

[Paul Moore](https://mail.python.org/archives/users/ad93c40b318f49d5b592f4b459c5a91d/) suggested that if a type be added to `**kwargs` then type checkers would be allowed and infer what it accepts. In this case the example would be:

```python
def some_function(f1: int):
    assert isinstance(f1, int)

def other_function(f0: str, **kwargs: Any):
    assert isinstance(f0, str)
    some_function(**kwargs)

other_function(f0='a', f1='b')
```

`Any` just enables type checking for `**kwargs`. In principle any value is accepted, but a type checker would be allowed further analyze the code and warn if there are problems. This sounds like a reasonable solution and it seems to me that it doesn't contradict PEP 484. Though, I am not an expert so it is for others to judge. Anyway, I just wanted to throw out the idea.

As a side note, I have been developing [jsonargparse](github.com/omni-us/jsonargparse) which can be used for automatic creation of complex parsers based on [signatures](https://jsonargparse.readthedocs.io/en/stable/#classes-methods-and-functions). Inferring accepted keyword args and its types based on how `**kwargs` is used, to me seems like a natural feature to expect. jsonargparse 4.10.0.dev2 already supports many cases like this, see [AST resolver](https://jsonargparse.readthedocs.io/en/latest/#ast-resolver).

**Comment by JelleZijlstra** [comment] 2022-06-17 16:12
What is special about `**kwargs` here? It seems to me you could make much the same argument that the type checker could infer that `f0` is of type `str` in your example.

That's how type checking works in Haskell, so I'm sure Python type checkers could support such inference too, but:

- Explicit signatures are a feature, not a bug. I think one of the good things about Python type checking is that it forces you to make your signatures explicit, so that human readers of the code can easily understand how to call a function. Even in Haskell, where you are allowed to omit signatures, people typically write down the signature explicitly.
- Python's type system, unlike Haskell's, wasn't designed to always allow inference. There may be features that cannot be inferred by a type checker.
- This feature seems difficult to implement for type checkers, so adding it to the official type system would put a burden on type checker authors.

**Comment by mauvilsa** [comment] 2022-06-17 16:31
> What is special about `**kwargs` here? It seems to me you could make much the same argument that the type checker could infer that `f0` is of type `str` in your example.
>
> That's how type checking works in Haskell, so I'm sure Python type checkers could support such inference too, but:
> 
>     * Explicit signatures are a feature, not a bug. I think one of the good things about Python type checking is that it forces you to make your signatures explicit, so that human readers of the code can easily understand how to call a function. Even in Haskell, where you are allowed to omit signatures, people typically write down the signature explicitly.

The example is just the minimal one to illustrate the concept. The point is `**kwargs` is used extensively in python and it allows avoiding to repeat the same multiple times. Take for example class inheritance, one base class and multiple subclasses. The base `__init__` could define a bunch of parameters, and all the subclasses only need to forward `**kwargs`. Requiring all subclasses to explicitly define all parameters that the parent class already defines goes against "don't repeat yourself" principle.

>     * Python's type system, unlike Haskell's, wasn't designed to always allow inference. There may be features that cannot be inferred by a type checker.

I am not suggesting that it should always be inferred. Clearly there are cases in which it is not possible. But for the cases in which it is possible, why not warn users about their mistakes? After all, that is what type checkers are supposed to do.

>     * This feature seems difficult to implement for type checkers, so adding it to the official type system would put a burden on type checker authors.

Also I am not suggesting that this should be a mandatory feature that checkers must implement. It is up for them to decide if they do. As I mentioned, I already [implemented](https://jsonargparse.readthedocs.io/en/latest/#ast-resolver) this kind of inference, though not for static type checking. I don't think it is difficult. But anyway, being difficult is not a good reason to disallow it.

**Comment by erictraut** [comment] 2022-06-17 16:58
Inferring the type of an input parameter (whether it's `**kwargs` or some other parameter) from its use within a function would result in incomplete, unknown, or inaccurate types for all but the most trivial of examples. It would also be computationally very expensive at analysis time. In summary, it would be ineffective most of the time at finding any bugs, would produce false positives in some cases, and would significantly impact type analysis performance in many cases. As such, I don't think any Python type checker author would opt to implement this.

> Requiring all subclasses to explicitly define all parameters that the parent class already defines...

FWIW, pyright infers the types of input parameters for unannotated methods within a derived class if the corresponding method within the parent class has an annotated signature and the parameter names and counts match. This was implemented mainly because pyright is the basis for a language server (pylance), and inferred parameter types help improve signature help when typing the arguments for a call. For developers who are interested in type checking, we still recommend providing explicit type annotations for input parameters for all the reasons that Jelle mentions above.

**Comment by gvanrossum** [comment] 2022-06-17 16:59
I have to agree that you are very persistent, but so far I have not been convinced.

Just to help me understand, in the example you would like the type checker to constrain the type of `**kwargs` based on the calls in the body of the function, so that if e.g. the only call is to a function that just takes `f1: int`, the `**kwargs` must be restricted to `f1: int` (using the proposed PEP 692 this could be expressed as a `TypedDict` with just one field, `f1: int`).

Like everyone else in the various issues you have opened, I have to say, sorry, that is just not how static type checking is defined for Python. It is quite a fundamental principle that whatever is seem to be happening in the body of a function does not affect the function's signature. This principle is needed so that functions can be type-checked independently from each other, type stubs can be created, and so on.

In order to save everyone time I will just close the issue.

**Closed by gvanrossum** 2022-06-17 16:59 UTC
Labels: topic: feature
