### ISSUE TITLE
Union[TypedDict, TypedDict] only type checks simple dicts

### ISSUE THREAD

**Issue by illeatmyhat** [python/typing#719] opened 2020-04-29 06:11 UTC
I am attempting to use a `Union` of `TypedDict`s to provide a clean and well documented API surface for my end-users, but it only works to check if the input is a simple `dict`.
It does not check whether the actual keys or values are correct.

See this snippet for reproducibility:
```
from typing import Union
# from typing import Union, TypedDict
from typing_extensions import TypedDict

class CloudCredentials(TypedDict):
    api_key: str
    endpoint: str

class LocalCredentials(TypedDict):
    username: str
    password: str
    endpoint: str


class Client:
    def __init__(self, credentials: Union[CloudCredentials, LocalCredentials]):
        self.credentials = credentials
        # all ok because we need to manually type check
        print(self.credentials['api_key'])
        print(self.credentials['username'])
        print(self.credentials['password'])
        print(self.credentials['endpoint'])
        # no type check error?
        print(self.credentials['hahaha_doesnt_exist'])

if __name__ == '__main__':
    # good
    Client('obviously wrong')

    # good
    Client({
        'api_key': 'foo',
        'endpoint': 'bar'
    })

    # should be incorrect but no type check error
    Client({
        'api_key': 'foo',
        'username': 'bar',
        'password': 'baz',
        'endpoint': 'bum',
    })

    # outright incorrect but no type check error
    Client({
        'didnt_ask_for_this': 12345
    })
```

My development environment is Python 3.6.10, conda,
PyCharm 2020.1 (Community Edition) Build #PC-201.6668.115
`typing==3.7.4.1`
`typing_extensions==3.7.4.2`
`typing-inspect==0.5.0`

**Comment by JelleZijlstra** [comment] 2020-04-29 15:16
Sounds like you want to report a bug to PyCharm. This repo is to discuss new additions to the type system, but this looks like it's just a bug in the type checker you're using.

**Comment by illeatmyhat** [comment] 2020-04-29 15:44
I was about to do that at first but thought about it and it seemed like additions to the type checker would be something implemented by library authors

**Comment by srittau** [comment] 2021-11-04 12:39
Closing per @JelleZijlstra.

**Closed by srittau** 2021-11-04 12:39 UTC

**Comment by sobolevn** [comment] 2021-11-04 12:42
I can confirm that `mypy` will be supporting this after https://github.com/python/mypy/pull/11244
